name: Refresh Snapshots (Manual Only)

# Scheduling disabled to reduce Neon compute usage / prevent auto wake & quota consumption.
# Re-enable by adding a schedule block if needed.
on:
  workflow_dispatch:
    inputs:
      enable:
        description: 'Set to true to actually perform snapshot refresh (otherwise noop)'
        required: false
        default: 'false'

# Prevent overlapping executions if a previous run is still in flight
concurrency:
  group: refresh-snapshots
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate DATABASE_URL secret
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "DATABASE_URL secret is missing or empty." >&2
            exit 1
          fi
          echo "DATABASE_URL secret is present (not printing value)."

      # Intentionally skipping schema migrations here; frequent enum recreation attempts were failing.
      # Schema should be managed by a separate manual/CI workflow (build/test pipeline) not this cron.

      - name: Conditional snapshot refresh (manual)
        if: ${{ github.event.inputs.enable == 'true' }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production
        run: |
          set -e
          echo "Manual snapshot refresh starting..."
          for attempt in 1 2 3; do
            echo "Attempt $attempt running snapshot refresh..."
            if npm run snapshots:refresh; then
              echo "Snapshot refresh succeeded on attempt $attempt"; exit 0; fi
            echo "Snapshot refresh failed on attempt $attempt; sleeping before retry" >&2
            sleep 5
          done
          echo "Snapshot refresh failed after 3 attempts" >&2
          exit 1

      - name: Skipped (disabled or enable flag not true)
        if: ${{ github.event.inputs.enable != 'true' }}
        run: echo "Snapshots disabled (no schedule and enable flag != true)."
